<a href="https://colab.research.google.com/github/krishnasai272/DeepLearning/blob/main/ENCODER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#AUTO ENCODER
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
# Load data
data = load_digits()
X = data.data / 16.0
# Encoder
input_layer = Input(shape=(64,))
encoded = Dense(32, activation='relu')(input_layer)
encoded = Dense(16, activation='relu')(encoded)
# Decoder
decoded = Dense(32, activation='relu')(encoded)
decoded = Dense(64, activation='sigmoid')(decoded)
# Autoencoder
autoencoder = Model(input_layer, decoded)
autoencoder.compile(optimizer='adam',
                    loss='mse')
autoencoder.fit(X, X,
                epochs=50,
                batch_size=32)
# Reconstruction
reconstructed = autoencoder.predict(X)
print("Original:")
print(X[0])
print("Reconstructed:")
print(reconstructed[0])

Epoch 1/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1284
Epoch 2/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0710
Epoch 3/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0592
Epoch 4/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0491
Epoch 5/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0406
Epoch 6/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0346
Epoch 7/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0308
Epoch 8/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0284
Epoch 9/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0268
Epoch 10/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0254
Epoch 11/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0242
Epoch 12/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0231
Epoch 13/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0221
Epoch 14/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0213
Epoch 15/50
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0206
Epoch 16/50
57/57 ━

In [3]:
import numpy as np
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
# Student marks dataset
X = np.array([
    [85, 90, 88, 80, 92],
    [70, 75, 72, 78, 80],
    [95, 92, 96, 90, 94],
    [60, 65, 62, 70, 68],
    [88, 85, 90, 82, 91],
    [72, 78, 75, 76, 79]
])

# Normalize data (0-1 range)
X = X / 100.0
# Encoder
input_layer = Input(shape=(5,))
encoded = Dense(3, activation='relu')(input_layer)
# Bottleneck Layer
bottleneck = Dense(2, activation='relu')(encoded)
# Decoder
decoded = Dense(3, activation='relu')(bottleneck)
output_layer = Dense(5, activation='sigmoid')(decoded)
# Autoencoder Model
autoencoder = Model(input_layer, output_layer)
# Compile
autoencoder.compile(
    optimizer='adam',
    loss='mse'
)
# Train
autoencoder.fit(
    X,
    X,
    epochs=200,
    verbose=0
)
# Reconstruct Marks
reconstructed = autoencoder.predict(X)
print("\nOriginal Marks:")
print(X[0] * 100)
print("\nReconstructed Marks:")
print(reconstructed[0] * 100)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step

Original Marks:
[85. 90. 88. 80. 92.]

Reconstructed Marks:
[54.791706 54.807137 54.805225 54.798203 54.823315]


In [4]:
import numpy as np
# Set seed for reproducible results
np.random.seed(42)
# Student marks dataset (6 students, 4 subjects)
X = np.array([
    [85, 90, 88, 80],
    [70, 75, 72, 78],
    [95, 92, 96, 90],
    [60, 65, 62, 70],
    [88, 85, 90, 82],
    [72, 78, 75, 76]
], dtype=float)
# Normalize data (0-1 range)
X = X / 100.0
# Layer dimensions: 4 -> 3 -> 2 -> 3 -> 4
input_dim = 4
encoder_dim = 3
bottleneck_dim = 2
decoder_dim = 3
output_dim = 4
# Initialize Weights and Biases
W1 = np.random.randn(input_dim, encoder_dim) * 0.1
b1 = np.zeros((1, encoder_dim))
W2 = np.random.randn(encoder_dim, bottleneck_dim) * 0.1
b2 = np.zeros((1, bottleneck_dim))
W3 = np.random.randn(bottleneck_dim, decoder_dim) * 0.1
b3 = np.zeros((1, decoder_dim))
W4 = np.random.randn(decoder_dim, output_dim) * 0.1
b4 = np.zeros((1, output_dim))
# Activation function & derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-np.clip(x, -500, 500)))
def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1 - s)
# Train (2000 epochs)
epochs = 2000
learning_rate = 1.0
m = X.shape[0]
for epoch in range(epochs):
    # Forward Pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    bottleneck = sigmoid(z2)  # Compressed 2 features
    z3 = np.dot(bottleneck, W3) + b3
    a3 = sigmoid(z3)
    z4 = np.dot(a3, W4) + b4
    reconstructed = sigmoid(z4)
    # Backpropagation
    dz4 = (reconstructed - X) * sigmoid_derivative(z4)
    dW4 = np.dot(a3.T, dz4) / m
    db4 = np.sum(dz4, axis=0, keepdims=True) / m
    da3 = np.dot(dz4, W4.T)
    dz3 = da3 * sigmoid_derivative(z3)
    dW3 = np.dot(bottleneck.T, dz3) / m
    db3 = np.sum(dz3, axis=0, keepdims=True) / m
    dbottleneck = np.dot(dz3, W3.T)
    dz2 = dbottleneck * sigmoid_derivative(z2)
    dW2 = np.dot(a1.T, dz2) / m
    db2 = np.sum(dz2, axis=0, keepdims=True) / m
    da1 = np.dot(dz2, W2.T)
    dz1 = da1 * sigmoid_derivative(z1)
    dW1 = np.dot(X.T, dz1) / m
    db1 = np.sum(dz1, axis=0, keepdims=True) / m
    # Update weights
    W4 -= learning_rate * dW4
    b4 -= learning_rate * db4
    W3 -= learning_rate * dW3
    b3 -= learning_rate * db3
    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2
    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1
# Encode 4 marks down to 2 features
encoded_features = sigmoid(np.dot(sigmoid(np.dot(X, W1) + b1), W2) + b2)
# Reconstruct Marks
a1_test = sigmoid(np.dot(X, W1) + b1)
bottleneck_test = sigmoid(np.dot(a1_test, W2) + b2)
a3_test = sigmoid(np.dot(bottleneck_test, W3) + b3)
reconstructed = sigmoid(np.dot(a3_test, W4) + b4)
# Display Results
print("\nOriginal Marks:")
print(X[0] * 100)
print("\nEncoded 2 Features:")
print(encoded_features[0])
print("\nReconstructed Marks:")
print(np.round(reconstructed[0] * 100, 2))


Original Marks:
[85. 90. 88. 80.]

Encoded 2 Features:
[0.46984909 0.46785696]

Reconstructed Marks:
[78.33 80.83 80.5  79.33]
